### ISSUE TITLE
Trying to use it with mappMotion component

### ISSUE THREAD

**Issue by qdl49** [br-automation-com/mappCfg#2]
Hi ! Thank's a lot for this library. I was looking for a library which allows to read mapp parameters. I need to read the parameters "LowerLimit" and "UpperLimit" from an axis config in mappMotion. Can you help me ? The MpLink is not an **MpComIdentType**.
Thank  you by advance for you help.

**Comment by stephan1827** [comment]
Hi,
unfortunately, the function block does not support this, but there are better ways for motion configurations. To change this value at runtime, you can use the B&R function block MC_BR_ProcessParID_AcpAx and then write to par ID AXLIM_POS_SW_END (126) and AXLIM_NEG_SW_END (127)

**Comment by stephan1827** [comment]
I am sorry, but that question is not related to this project. Please contact your local B&R support for this question.
